"use client";

import { useState } from "react";
import { FaCopy, FaDownload, FaEdit, FaMagic } from "react-icons/fa";
import { MdDeleteOutline, MdMoreVert } from "react-icons/md";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Textarea } from "@/components/ui/textarea";
import { Label } from "@/components/ui/label";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import { toast } from "@/components/ui/toast";
import { usePersistentState } from "@/hooks/usePersistentState";
import type { ConversationPoint } from "@/lib/types";

interface PromptPanelProps {
  conversationPoints: ConversationPoint[];
  onSend: (modificationPrompt: string) => void;
  isLoading: boolean;
  selectedPromptIndex: number | null;
  onPromptSelect: (pointIndex: number) => void;
  onDeletePoint: (pointIndex: number) => void;
  onClone: (pointIndex: number) => void;
  screenName: string | null;
  screenId: string;
  getHtmlForPoint: (pointIndex: number) => string;
}

export default function PromptPanel({
  conversationPoints,
  onSend,
  isLoading,
  selectedPromptIndex,
  onPromptSelect,
  onDeletePoint,
  onClone,
  screenName,
  screenId,
  getHtmlForPoint,
}: PromptPanelProps) {
  const [isEditing, setIsEditing] = useState(false);
  const [editValue, setEditValue] = usePersistentState<string>(
    `promptEdit-${screenId}`,
    "",
    300,
  );
  const [confirmDeleteIndex, setConfirmDeleteIndex] = useState<number | null>(null);

  const handleModify = () => {
    setIsEditing(true);
    // Don't clear editValue - preserve any previously entered text
  };

  const handleCreate = () => {
    if (!editValue.trim()) return;
    onSend(editValue);
    setIsEditing(false);
    setEditValue("");
  };

  const handleKeyPress = (e: React.KeyboardEvent<HTMLTextAreaElement>) => {
    if (e.key === "Enter" && (e.ctrlKey || e.metaKey)) {
      e.preventDefault();
      handleCreate();
    }
  };

  const handleBlur = () => {
    // If the field is empty (after trimming), cancel the modify flow
    // Otherwise, just exit editing mode but preserve the text
    if (!editValue.trim()) {
      setIsEditing(false);
      setEditValue("");
    } else {
      // Exit editing mode but keep the text for next time
      setIsEditing(false);
    }
  };

  const handleDeleteClick = (index: number) => {
    setConfirmDeleteIndex(index);
  };

  const handleConfirmDelete = () => {
    if (confirmDeleteIndex !== null) {
      onDeletePoint(confirmDeleteIndex);
      setConfirmDeleteIndex(null);
    }
  };

  const handleCancelDelete = () => {
    setConfirmDeleteIndex(null);
  };

  const handleCloneClick = (index: number) => {
    onClone(index);
  };

  const handleExportClick = async (index: number) => {
    try {
      const html = getHtmlForPoint(index);
      if (!html) {
        toast("No HTML content available for this conversation point");
        return;
      }

      // Get all prompts up to and including this point
      const prompts = conversationPoints
        .slice(0, index + 1)
        .map((point) => point.prompt)
        .filter((prompt) => prompt.trim());

      // Format the prompt history comment
      const promptHistory = prompts
        .map((prompt) => `(${prompt})`)
        .join("\n\n--\n\n");

      // Create the formatted HTML with prompt history comment
      const formattedHtml = `<!-- 

This file was generated by UI Generator model, using this prompts:

${promptHistory}

-->

${html}`;

      // Copy to clipboard
      await navigator.clipboard.writeText(formattedHtml);

      // Show toast notification
      const displayName = screenName || "Screen";
      toast(`${displayName} is copied to clipboard`);
    } catch (error) {
      console.error("Failed to copy to clipboard:", error);
      toast("Failed to copy to clipboard");
    }
  };

  return (
    <div className="absolute left-full z-10 ml-2 max-h-[844px] w-64 overflow-x-visible overflow-y-auto">
      <div className="flex flex-col gap-2">
        {/* Display all conversation points (prompts) */}
        {conversationPoints.map((point, index) => {
          const isLastEntry = index === conversationPoints.length - 1;
          return (
            <div key={index} className="group flex items-center gap-1">
              <Card
                onClick={() => onPromptSelect(index)}
                className={`flex-1 cursor-pointer px-3 py-2 text-xs transition-colors ${selectedPromptIndex === index
                  ? "border-primary bg-accent text-primary peer-hover:border-destructive peer-hover:bg-destructive/10"
                  : "hover:border-primary hover:bg-accent peer-hover:border-destructive peer-hover:bg-destructive/10"
                  }`}
              >
                {point.prompt}
              </Card>
              {/* Dropdown menu */}
              <div className="flex w-6 flex-shrink-0 items-center justify-center">
                <DropdownMenu>
                  <DropdownMenuTrigger asChild>
                    <Button
                      variant="ghost"
                      size="icon-sm"
                      className="relative h-6 w-6 p-0 opacity-0 transition-opacity group-hover:opacity-100"
                      onClick={(e) => e.stopPropagation()}
                    >
                      <MdMoreVert className="text-sm" />
                    </Button>
                  </DropdownMenuTrigger>
                  <DropdownMenuContent align="end" onClick={(e) => e.stopPropagation()}>
                    <DropdownMenuItem onClick={() => handleExportClick(index)}>
                      <FaDownload className="mr-2 h-4 w-4" />
                      <span>Export to clipboard</span>
                    </DropdownMenuItem>
                    <DropdownMenuItem onClick={() => handleCloneClick(index)}>
                      <FaCopy className="mr-2 h-4 w-4" />
                      <span>Clone</span>
                    </DropdownMenuItem>
                    {isLastEntry && (
                      <DropdownMenuItem
                        variant="destructive"
                        onClick={() => handleDeleteClick(index)}
                      >
                        <MdDeleteOutline className="mr-2 h-4 w-4" />
                        <span>Delete</span>
                      </DropdownMenuItem>
                    )}
                  </DropdownMenuContent>
                </DropdownMenu>
              </div>
            </div>
          );
        })}

        {/* Confirmation popup */}
        <Dialog
          open={confirmDeleteIndex !== null}
          onOpenChange={(open) => !open && handleCancelDelete()}
        >
          <DialogContent className="sm:max-w-[425px]">
            <DialogHeader>
              <DialogTitle>Are you sure?</DialogTitle>
              <DialogDescription>
                This action cannot be undone. This will permanently delete this conversation point.
              </DialogDescription>
            </DialogHeader>
            <DialogFooter>
              <Button variant="outline" onClick={handleCancelDelete}>
                Cancel
              </Button>
              <Button variant="destructive" onClick={handleConfirmDelete}>
                Delete
              </Button>
            </DialogFooter>
          </DialogContent>
        </Dialog>

        {/* Modify button or edit form */}
        {isEditing ? (
          <div className="flex flex-col gap-2">
            <Label htmlFor="modify-textarea" className="text-xs">
              What you would like to change
            </Label>
            <Textarea
              id="modify-textarea"
              value={editValue}
              onChange={(e) => setEditValue(e.target.value)}
              onKeyDown={handleKeyPress}
              onBlur={handleBlur}
              placeholder="Describe the modification..."
              rows={4}
              className="text-xs bg-secondary dark:bg-secondary"
              disabled={isLoading}
            />
            <Button
              onClick={handleCreate}
              disabled={isLoading || !editValue.trim()}
              className="flex items-center justify-center gap-2 text-xs"
            >
              <FaMagic />
              <span>Create</span>
            </Button>
          </div>
        ) : (
          <Button
            onClick={handleModify}
            disabled={isLoading}
            variant="ghost"
            size="sm"
            className="self-start text-xs"
          >
            <FaEdit className="text-xs" />
            <span>Modify</span>
          </Button>
        )}
      </div>
    </div>
  );
}
